using System.Globalization;
using Flint.Protocol;
using Shouldly;

namespace Flint.Protocol.Tests;

/// <summary>
/// Every browser enum must agree with the committed manifest, value for value.
/// </summary>
/// <remarks>
/// The golden corpus proves that three implementations encode the same <em>messages</em> to the
/// same bytes. It cannot prove they agree on the values those messages may carry — a vector only
/// exercises the values it happens to use, and most of them are used by none.
///
/// That gap has teeth here in particular: this codec resolves enums reflectively, so a value added
/// on the C# side alone encodes happily and is rejected by Rust and Kotlin. Nothing would catch it
/// until someone pressed the button on a television.
///
/// The manifest is generated by Rust and committed under <c>testdata/golden/</c>. It records wire
/// values rather than names on purpose: the three languages spell the same value differently
/// (<c>SetUa</c> / <c>SetUserAgent</c>, <c>Tv</c> / <c>Television</c>), and only the number crosses
/// the wire.
/// </remarks>
public sealed class BrowserEnumManifestTests
{
    [Fact]
    public void EveryEnumInTheManifestExistsHereWithTheSameWireValues()
    {
        var manifest = ReadManifest();
        manifest.ShouldNotBeEmpty();

        foreach (var (name, expected) in manifest)
        {
            var type = FindEnum(name);
            type.ShouldNotBeNull($"{name} is in the manifest but not declared in Flint.Protocol");

            var actual = Enum.GetValues(type)
                .Cast<object>()
                .Select(value => Convert.ToInt32(value, CultureInfo.InvariantCulture))
                .OrderBy(value => value)
                .ToArray();

            actual.ShouldBe(
                expected,
                $"{name} wire values differ from the committed manifest. If this is a deliberate "
                + "protocol change, regenerate with: "
                + "cargo test --test enum_manifest -- --ignored regenerate");
        }
    }

    [Fact]
    public void NoBrowserEnumHereIsMissingFromTheManifest()
    {
        // The other direction. An enum added on this side without regenerating would otherwise be
        // invisible to the check above, and so checked by no other language.
        var manifest = ReadManifest();
        var unlisted = typeof(BrowserCommandAction).Assembly
            .GetTypes()
            .Where(type => type.IsEnum && type.Name.StartsWith("Browser", StringComparison.Ordinal))
            .Select(type => type.Name)
            .Where(name => !manifest.ContainsKey(name))
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToArray();

        unlisted.ShouldBeEmpty(
            "these browser enums are absent from the committed manifest, so no other language is "
            + "checking them: " + string.Join(", ", unlisted));
    }

    private static Type? FindEnum(string name) => typeof(BrowserCommandAction).Assembly
        .GetTypes()
        .FirstOrDefault(type => type.IsEnum && type.Name == name);

    private static Dictionary<string, int[]> ReadManifest()
    {
        var path = Path.Combine(GoldenVectors.Directory(), "browser-enums.txt");
        File.Exists(path).ShouldBeTrue(
            $"missing {path}. Generate it with: "
            + "cargo test --test enum_manifest -- --ignored regenerate");

        return File.ReadAllLines(path)
            .Where(line => line.Length > 0)
            .Select(line => line.Split('=', 2))
            .ToDictionary(
                parts => parts[0],
                parts => parts[1]
                    .Split(',', StringSplitOptions.RemoveEmptyEntries)
                    .Select(value => int.Parse(value, CultureInfo.InvariantCulture))
                    .ToArray(),
                StringComparer.Ordinal);
    }
}
