package com.rextechnologies.flint.receiver.browser

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Authenticated encryption for the private portion of a persisted browser-network setting.
 *
 * The store deliberately owns the file format; this small boundary lets its policy be covered by
 * ordinary JVM tests while the receiver uses Android Keystore in production. Implementations must
 * reject authentication failures rather than returning guessed plaintext.
 */
interface BrowserNetworkCrypto {
    @Throws(BrowserNetworkCryptoException::class)
    fun encrypt(plaintext: ByteArray, associatedData: ByteArray): BrowserNetworkCiphertext

    @Throws(BrowserNetworkCryptoException::class)
    fun decrypt(ciphertext: BrowserNetworkCiphertext, associatedData: ByteArray): ByteArray
}

/** Ciphertext envelope before its bounded Base64 representation is written by the store. */
class BrowserNetworkCiphertext(
    initializationVector: ByteArray,
    encryptedBytes: ByteArray,
) {
    val initializationVector: ByteArray = initializationVector.copyOf()
    val encryptedBytes: ByteArray = encryptedBytes.copyOf()
}

class BrowserNetworkCryptoException(message: String, cause: Throwable? = null) : Exception(message, cause)

/**
 * AES-256-GCM backed by an app-scoped, non-exportable Android Keystore key.
 *
 * A fresh random IV is generated by the platform cipher for every write. The key is intentionally
 * not eligible for a portable fallback: if Android Keystore is unavailable or invalidated, stored
 * VPN credentials fail closed and must be provisioned again rather than falling back to plaintext.
 */
class AndroidKeystoreBrowserNetworkCrypto(
    private val keyAlias: String = DEFAULT_KEY_ALIAS,
) : BrowserNetworkCrypto {
    override fun encrypt(plaintext: ByteArray, associatedData: ByteArray): BrowserNetworkCiphertext {
        val key = loadOrCreateKey()
        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, key)
            cipher.updateAAD(associatedData)
            BrowserNetworkCiphertext(cipher.iv, cipher.doFinal(plaintext))
        } catch (error: Throwable) {
            throw BrowserNetworkCryptoException("Could not encrypt browser VPN credentials", error)
        }
    }

    override fun decrypt(ciphertext: BrowserNetworkCiphertext, associatedData: ByteArray): ByteArray {
        val key = loadOrCreateKey()
        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(
                Cipher.DECRYPT_MODE,
                key,
                GCMParameterSpec(GCM_TAG_BITS, ciphertext.initializationVector),
            )
            cipher.updateAAD(associatedData)
            cipher.doFinal(ciphertext.encryptedBytes)
        } catch (error: Throwable) {
            throw BrowserNetworkCryptoException("Could not decrypt browser VPN credentials", error)
        }
    }

    private fun loadOrCreateKey(): SecretKey = synchronized(keyLock) {
        try {
            val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
            (keyStore.getKey(keyAlias, null) as? SecretKey)?.let { return@synchronized it }

            KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE).apply {
                init(
                    KeyGenParameterSpec.Builder(
                        keyAlias,
                        KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
                    )
                        .setKeySize(KEY_SIZE_BITS)
                        .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                        .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                        .setRandomizedEncryptionRequired(true)
                        .setUserAuthenticationRequired(false)
                        .build(),
                )
            }.generateKey()
        } catch (error: Throwable) {
            throw BrowserNetworkCryptoException("Android Keystore is unavailable", error)
        }
    }

    private companion object {
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val DEFAULT_KEY_ALIAS = "flint.browser-network.v2"
        const val KEY_SIZE_BITS = 256
        const val GCM_TAG_BITS = 128
        val keyLock = Any()
    }
}
